//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowersShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flower
    {
        public int FlowerId { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string Article { get; set; }
    }
}
